site_name: AchievAIm
site_description: AchievAIm landing page
site_url: https://achievaim.com

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/favicon.ico
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: slate
      primary: blue
      accent: white
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: default
      primary: blue
      accent: white
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - search.suggest
    - search.highlight
repo_name: Achiev𝘼𝙄m
repo_url: https://github.com/xyvora/achievaim


nav:
  - Home: "index.md"

plugins:
  - mkdocs-video:
      is_video: True
      video_autoplay: False
      video_controls: True
      css_style:
        width: "100%"

extra:
  generator: false
